from typing import Protocol, runtime_checkable


@runtime_checkable
class FileStreamProtocol(Protocol):
    def read(self, size: int = -1, /) -> bytes: ...

    def seek(self, offset: int, whence: int = 0, /) -> int: ...

    def tell(self) -> int: ...

    def close(self) -> None: ...
