services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mypg
      POSTGRES_USER: mypg
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "54320:5432"

volumes:
  pgdata: