"""
This type stub file was generated by pyright.
"""

from PIL import Image

def get_image_hash(pil_image: Image.Image) -> str:
    """Generate a hash for the image to use as cache key."""
    ...

def get_text_hash(text: str | None) -> str | None:
    """Return a deterministic SHA-256 hash for *text*.

    Returns None if *text* is ``None`` so callers can pass the value
    directly into ``generate_hash`` without extra conditionals.
    """
    ...

