path: ''
name: default_dataset
force_download: false
trust_remote_code: true
keep_in_memory: false
num_proc: 8
split: train
streaming: false
seed: 42
eval_size: 0.2
test_size: 0.1
column_map:
  image_column: image
  ground_truth_column: ground_truth
  boxes_column: bboxes
  labels_column: labels
  tokens_column: tokens
