x-logging:
  logging: &default-logging
    driver: "local"
    options:
      max-size: "10m"
      max-file: "3"

services:
  label-studio:
    image: heartexlabs/services:latest
    restart: unless-stopped
    container_name: services-prod
    ports:
      - "8080:8080"
    env_file:
      - .env.prod
    command: services-uwsgi
    depends_on:
      - db
      - minio

  ml-backend:
    container_name: services-ml-backend-prod
    build:
      context: ./backends/${LABEL_STUDIO_ML_BACKEND} 
      args:
        TEST_ENV: ${TEST_ENV}
    ports:
      - "9090:9090"
    volumes:
      - ./backends/${LABEL_STUDIO_ML_BACKEND}:/app:rw
    env_file:
      - .env.prod
    # command: >
    #   services-ml start .
    #     --host 0.0.0.0 --port 9090
    #command: gunicorn --preload -w ${GUNICORN_WORKERS:-1} --threads ${GUNICORN_THREADS:-1} --chdir /app -b 0.0.0.0:9090 _wsgi:app  --worker-class sync
    command: >
      gunicorn --chdir /app _wsgi:app --bind 0.0.0.0:9090 --workers 2 --threads 8 --worker-class gthread --timeout 300 --access-logfile "-"

  db:
    image: pgautoupgrade/pgautoupgrade:13-alpine
    hostname: db
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d:ro
    env_file:
      - .env.prod
    ports:
      - "5433:5432"

  minio:
    image: quay.io/minio/minio:latest
    command: server /data --address ":9007" --console-address ":9006"
    restart: unless-stopped
    logging: *default-logging
    healthcheck:
      test: mc ready local 
      interval: 5s
      timeout: 5s
      retries: 3
    ports:
      - "9007:9007"
      - "9006:9006"
    volumes:
      - minio-data:/data
    env_file:
      - .env.prod

  minio-sync:
    image: minio/mc:latest
    env_file: 
      - .env.prod
    depends_on:
      minio:
        condition: service_healthy
    volumes:
      - ./sync-minio.sh:/scripts/sync-minio.sh
      - app-data:/data:rw
    entrypoint: /bin/sh -c "/scripts/sync-minio.sh"
    restart: "no"
    profiles: ["sync"]

  dataset-sync:
    build:
      context: ./dataset_sync
      dockerfile: Dockerfile
    container_name: data-sync-dev
    restart: unless-stopped
    logging: *default-logging
    depends_on:
      - minio
    volumes:
      - app-data:/data:rw
      - ./dataset_sync:/app
      - ./.env.prod:/app/config/.env.prod
    env_file:
      - .env.prod
    command: ["/bin/bash", "-c", "/app/setup_data.sh && python dataset_sync.py --loop --env_file /app/config/.env.prod"]

  prometheus:
    image: quay.io/prometheus/prometheus:v2.37.1
    restart: unless-stopped
    logging: *default-logging
    ports:
      - "9099:9099"
    volumes:
      - "./prometheus/minio/prometheus.yaml:/etc/prometheus/prometheus.yaml"
      - "prometheus-data:/prometheus"
    env_file:
      - .env.prod
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"



volumes:
  minio-data:
  prometheus-data:
  app-data:  # Added named volume for application data
