"""
This type stub file was generated by pyright.
"""

class ConfigFileNotFoundError(Exception):
    """Raise when specified config file is not found."""
    def __init__(self, config_name, config_type, available_configs) -> None:
        ...
    


class ConfigNotRegisteredError(Exception):
    """Raise when specified config is not registered."""
    def __init__(self, config_type, config_subtype, registered_configs) -> None:
        ...
    


class InvalidConfigType(Exception):
    """Raise when specified config type is invalid."""
    def __init__(self, config_type, available_config_types) -> None:
        ...
    


class InvalidConfigSubtype(Exception):
    """Raise when specified config subtype is invalid."""
    def __init__(self, config_type, config_subtype, supported_subtypes) -> None:
        ...
    


class ConfigValidationError(Exception):
    """Raise when config validation fails."""
    def __init__(self, message) -> None:
        ...
    


class DataTypeMismatchError(Exception):
    """Exception raised when there is a type mismatch between pipeline steps or phases.
    
    Attributes:
        step: The pipeline step or phase where the mismatch occurred
        produced_type: The type produced by the previous step/phase
        consumed_type: The type expected by the current step/phase
    """
    def __init__(self, location, output_type, input_type) -> None:
        ...
    


