"""
This type stub file was generated by pyright.
"""

import torch

logger = ...
def unnormalize_bbox(bbox, width, height): # -> list[Any]:
    ...

def get_model_and_processor(cfg): # -> tuple[LayoutLMv3ForTokenClassification, Any]:
    ...

def sliding(processor, token_boxes, predictions, encoding, width, height): # -> tuple[list[Any], list[Any], list[str]]:
    ...

@torch.no_grad()
def retrieve_predictions(image, processor, model, words=..., bboxes=...): # -> tuple[list[Any], list[Any], list[str]]:
    """
    Retrieve predictions_data for a single example.

    Return:
        boxes
        preds
        flattened_words
    """
    ...

