"""
This type stub file was generated by pyright.
"""

from pathlib import Path

"""Shared utilities used across the project.

This module defines :pydata:`REPOSITORY_ROOT` and related paths in a way that
does **not** require the presence of a ``.git`` directory inside production
containers.  The logic is:

1.  If an environment variable ``PROJECT_ROOT`` (or the historical
    ``AI_OSRODEK_ROOT``) is set, use it.
2.  Otherwise, walk upwards from the current file looking for a *marker* file
    that always exists in the repository, namely ``pyproject.toml``.
3.  As a last resort (for local development clones) fall back to detecting the
    ``.git`` directory.

This approach keeps containers lightweight (no need to mount or COPY the full
``.git`` history) while still allowing source checkouts to work seamlessly on
developer machines.
"""
def find_repository_root(start: str | Path | None = ...) -> Path:
    """Robustly detect the project root directory.

    The search order is:
    1. `PROJECT_ROOT` env var.
    2. Upwards walking search for ``pyproject.toml``.
    """
    ...

REPOSITORY_ROOT: Path = ...
TMP_DIR = ...
CONFIGS_DIR = ...
MAPPINGS_DIR = ...
