"""
This type stub file was generated by pyright.
"""

from typing import List

"""
BIO Parsing Utilities for Ecclesiastical Schematisms

This module provides utilities to convert BIO-tagged annotations into structured JSON
file_format for ecclesiastical schematism documents.
"""

def bio_to_spans(words: List[str], labels: List[str]) -> List[tuple]:
    """
    Convert parallel `words`, `labels` (BIO) into a list of
    (entity_type, "concatenated text") tuples.
    """
    ...

def sort_by_layout(
    words, bboxes, labels
):  # -> tuple[Any, Any] | tuple[list[Any], list[Any]]:
    """Sort words in reading order (top-to-bottom, left-to-right)"""
    ...

def repair_bio_labels(labels):  # -> list[Any]:
    ...

def build_page_json(words, bboxes, labels):  # -> dict[str, Any]:
    """
    Build the target JSON structure from BIO-tagged annotations.

    Expected output file_format:
    {
      "page_number": "<string | null>",
      "deanery": "<string | null>",
      "entries": [
        {
          "parish": "<string>",
          "dedication": "<string>",
          "building_material": "<string>"
        },
        ...
      ]
    }
    """
    ...
