import * as stylex from "@stylexjs/stylex";

import { tokens } from "@/lib/stylex/tokens.stylex";

export const workbenchStyles = stylex.create({
  /* Sits beside the docked workspace rail; floating chrome anchors to this box. */
  shell: {
    position: "relative",
    marginInlineStart: "var(--ns-rail-width, 0px)",
    width: "calc(100% - var(--ns-rail-width, 0px))",
    height: "100svh",
    overflow: "hidden",
    backgroundColor: tokens.colorBg,
    color: tokens.colorText,
  },
  canvas: { position: "absolute", inset: 0 },
  toolButton: {
    height: "31px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "6px",
    paddingInline: "9px",
    borderWidth: 0,
    borderRadius: "5px",
    backgroundColor: { default: "transparent", ":hover": tokens.colorHover, ":disabled": "transparent" },
    color: { default: tokens.colorMuted, ":disabled": tokens.colorTextDisabled },
    cursor: { default: "pointer", ":disabled": "not-allowed" },
    fontSize: tokens.fontSizeSm,
  },
  primaryButton: {
    backgroundColor: {
      default: tokens.colorAccent,
      ":hover": tokens.colorAccentHover,
      ":disabled": tokens.colorAccentDisabled,
    },
    color: { default: tokens.colorOnAccent, ":disabled": tokens.colorTextDisabled },
    fontWeight: 700,
  },
  /* Canvas tools dock over the canvas; the left edge belongs to app navigation. */
  toolDock: {
    position: "absolute",
    zIndex: 20,
    bottom: "18px",
    left: "50%",
    display: "flex",
    alignItems: "center",
    gap: "2px",
    padding: "6px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.colorBorder,
    borderRadius: "12px",
    backgroundColor: tokens.colorChrome,
    boxShadow: tokens.shadowNode,
    transform: "translateX(-50%)",
  },
  railButton: {
    position: "relative",
    flexShrink: 0,
    width: "34px",
    height: "34px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    paddingInline: 0,
    borderWidth: 0,
    borderRadius: "6px",
    backgroundColor: {
      default: "transparent",
      ":hover": tokens.colorHover,
      ":disabled": "transparent",
    },
    color: {
      default: tokens.colorMuted,
      ":hover": tokens.colorTextEmphasis,
      ":disabled": tokens.colorTextDisabled,
    },
    cursor: { default: "pointer", ":disabled": "not-allowed" },
    transitionDuration: "120ms",
    transitionProperty: "background-color, color",
  },
  railMenuButton: {
    width: "100%",
    justifyContent: "flex-start",
    gap: "8px",
    paddingInline: "9px",
    fontSize: tokens.fontSizeSm,
    fontWeight: 650,
    textAlign: "left",
  },
  railPrimary: {
    backgroundColor: {
      default: tokens.colorAccentSoft,
      ":hover": tokens.colorAccentSoft,
    },
    color: { default: tokens.colorAccent, ":hover": tokens.colorAccent },
  },
  railDanger: {
    backgroundColor: {
      default: "transparent",
      ":hover": tokens.colorDangerHover,
      ":disabled": "transparent",
    },
    color: {
      default: tokens.colorMuted,
      ":hover": tokens.colorDanger,
      ":disabled": tokens.colorTextDisabled,
    },
  },
  /* Kept in the DOM so each icon button still has an accessible name. */
  railLabel: {
    position: "absolute",
    width: "1px",
    height: "1px",
    margin: "-1px",
    padding: 0,
    overflow: "hidden",
    clipPath: "inset(50%)",
    whiteSpace: "nowrap",
  },
  railMenuLabel: {
    position: "static",
    width: "auto",
    height: "auto",
    margin: 0,
    overflow: "visible",
    clipPath: "none",
  },
  railDivider: {
    width: "1px",
    height: "20px",
    flexShrink: 0,
    marginInline: "4px",
    backgroundColor: tokens.colorDivider,
  },
  shapesMenuWrap: {
    position: "relative",
    display: "flex",
  },
  shapesMenu: {
    position: "absolute",
    left: 0,
    bottom: "calc(100% + 8px)",
    display: "grid",
    gap: "3px",
    minWidth: "132px",
    padding: "6px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.colorBorder,
    borderRadius: "12px",
    backgroundColor: tokens.colorChrome,
    boxShadow: tokens.shadowNode,
  },
  selectionToolbar: {
    zIndex: 25,
    minHeight: "42px",
    display: "flex",
    alignItems: "center",
    gap: "3px",
    padding: "5px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.colorBorderStrong,
    borderRadius: "12px",
    backgroundColor: tokens.colorChrome,
    boxShadow: tokens.shadowNodeSelected,
    pointerEvents: "auto",
  },
  selectionLabel: {
    paddingInline: "7px 9px",
    color: tokens.colorSubtle,
    fontSize: tokens.fontSizeXs,
    fontWeight: 700,
    whiteSpace: "nowrap",
  },
  selectionDivider: {
    width: "1px",
    height: "24px",
    marginInline: "2px",
    backgroundColor: tokens.colorDivider,
  },
  visuallyHidden: {
    position: "absolute",
    width: "1px",
    height: "1px",
    padding: 0,
    margin: "-1px",
    overflow: "hidden",
    borderWidth: 0,
    clip: "rect(0, 0, 0, 0)",
    whiteSpace: "nowrap",
  },
  spinner: {
    animationName: "ns-spin",
    animationDuration: "900ms",
    animationIterationCount: "infinite",
    animationTimingFunction: "linear",
  },
});
