from collections.abc import Iterable
from typing import Protocol
from uuid import UUID

from notarius_core.domain.models.studio import (
    Job,
    JobItem,
    JobStatus,
    OutputSchema,
    Project,
    Recipe,
    Source,
    SourceItem,
)
from notarius_core.domain.models.platform import (
    Artifact,
    ArtifactSequence,
    Experiment,
    InputAssemblyTrace,
    InvocationTrace,
    NodeRun,
    NodeRunStatus,
    OutboxMessage,
    OutboxMessageStatus,
    WorkflowDefinition,
    WorkflowRun,
    WorkflowRunStatus,
    WorkflowVersion,
)


class ProjectRepositoryPort(Protocol):
    async def add(self, project: Project) -> None: ...
    async def get(self, project_id: UUID) -> Project | None: ...
    async def list(self) -> list[Project]: ...


class SourceRepositoryPort(Protocol):
    async def add(self, source: Source) -> None: ...
    async def get(self, source_id: UUID) -> Source | None: ...
    async def list_for_project(self, project_id: UUID) -> list[Source]: ...


class SourceItemRepositoryPort(Protocol):
    async def add(self, item: SourceItem) -> None: ...
    async def add_batch(self, items: list[SourceItem]) -> None: ...
    async def get(self, item_id: UUID) -> SourceItem | None: ...
    async def list_for_source(self, source_id: UUID) -> list[SourceItem]: ...


class OutputSchemaRepositoryPort(Protocol):
    async def add(self, schema: OutputSchema) -> None: ...
    async def get(self, schema_id: UUID) -> OutputSchema | None: ...
    async def list_for_project(self, project_id: UUID) -> list[OutputSchema]: ...


class RecipeRepositoryPort(Protocol):
    async def add(self, recipe: Recipe) -> None: ...
    async def get(self, recipe_id: UUID) -> Recipe | None: ...
    async def list_for_project(self, project_id: UUID) -> list[Recipe]: ...


class JobRepositoryPort(Protocol):
    async def add(self, job: Job) -> None: ...
    async def get(self, job_id: UUID) -> Job | None: ...
    async def next_queued(self) -> Job | None: ...
    async def update(self, job: Job) -> None: ...
    async def list_for_project(self, project_id: UUID) -> list[Job]: ...
    async def list_by_status(self, status: JobStatus) -> list[Job]: ...


class JobItemRepositoryPort(Protocol):
    async def add(self, job_item: JobItem) -> None: ...
    async def add_batch(self, job_items: list[JobItem]) -> None: ...
    async def get(self, job_item_id: UUID) -> JobItem | None: ...
    async def list_for_job(self, job_id: UUID) -> list[JobItem]: ...
    async def update(self, job_item: JobItem) -> None: ...


class WorkflowDefinitionRepositoryPort(Protocol):
    async def add(self, definition: WorkflowDefinition) -> None: ...
    async def get(self, definition_id: UUID) -> WorkflowDefinition | None: ...
    async def update(self, definition: WorkflowDefinition) -> None: ...
    async def list(self) -> list[WorkflowDefinition]: ...


class WorkflowVersionRepositoryPort(Protocol):
    async def add(self, version: WorkflowVersion) -> None: ...
    async def get(self, version_id: UUID) -> WorkflowVersion | None: ...
    async def list_for_definition(
        self,
        definition_id: UUID,
    ) -> list[WorkflowVersion]: ...
    async def latest_for_definition(
        self,
        definition_id: UUID,
    ) -> WorkflowVersion | None: ...


class WorkflowRunRepositoryPort(Protocol):
    async def add(self, run: WorkflowRun) -> None: ...
    async def get(self, run_id: UUID) -> WorkflowRun | None: ...
    async def update(self, run: WorkflowRun) -> None: ...
    async def next_queued(self) -> WorkflowRun | None: ...
    async def list_for_version(self, version_id: UUID) -> list[WorkflowRun]: ...
    async def list_by_status(self, status: WorkflowRunStatus) -> list[WorkflowRun]: ...


class ExperimentRepositoryPort(Protocol):
    async def add(self, experiment: Experiment) -> None: ...
    async def get(self, experiment_id: UUID) -> Experiment | None: ...
    async def update(self, experiment: Experiment) -> None: ...
    async def list_for_workflow_version(
        self,
        workflow_version_id: UUID,
    ) -> list[Experiment]: ...
    async def list(self) -> list[Experiment]: ...


class NodeRunRepositoryPort(Protocol):
    async def add(self, node_run: NodeRun) -> None: ...
    async def add_batch(self, node_runs: list[NodeRun]) -> None: ...
    async def get(self, node_run_id: UUID) -> NodeRun | None: ...
    async def update(self, node_run: NodeRun) -> None: ...
    async def next_queued(self) -> NodeRun | None: ...
    async def list_for_workflow_run(self, workflow_run_id: UUID) -> list[NodeRun]: ...
    async def list_by_status(self, status: NodeRunStatus) -> list[NodeRun]: ...


class ArtifactRepositoryPort(Protocol):
    async def add(self, artifact: Artifact) -> None: ...
    async def get(self, artifact_id: UUID) -> Artifact | None: ...
    async def list_for_source(self, source_id: UUID) -> list[Artifact]: ...
    async def list_for_workflow_run(self, workflow_run_id: UUID) -> list[Artifact]: ...
    async def list_for_node_run(self, node_run_id: UUID) -> list[Artifact]: ...
    async def list_by_type(self, artifact_type: str) -> list[Artifact]: ...


class ArtifactSequenceRepositoryPort(Protocol):
    async def add(self, sequence: ArtifactSequence) -> None: ...
    async def get(self, sequence_id: UUID) -> ArtifactSequence | None: ...
    async def list_for_source(self, source_id: UUID) -> list[ArtifactSequence]: ...
    async def list_by_artifact_type(
        self,
        artifact_type: str,
    ) -> list[ArtifactSequence]: ...


class InputAssemblyTraceRepositoryPort(Protocol):
    async def add(self, trace: InputAssemblyTrace) -> None: ...
    async def list_for_node_run(
        self, node_run_id: UUID
    ) -> list[InputAssemblyTrace]: ...


class InvocationTraceRepositoryPort(Protocol):
    async def add(self, trace: InvocationTrace) -> None: ...
    async def list_for_node_run(self, node_run_id: UUID) -> list[InvocationTrace]: ...


class OutboxMessageRepositoryPort(Protocol):
    async def add(self, message: OutboxMessage) -> None: ...
    async def get(self, message_id: UUID) -> OutboxMessage | None: ...
    async def update(self, message: OutboxMessage) -> None: ...
    async def delete_many(self, message_ids: Iterable[UUID]) -> int: ...
    async def list_for_workflow_run(
        self,
        workflow_run_id: UUID,
    ) -> list[OutboxMessage]: ...
    async def list_by_status(
        self,
        status: OutboxMessageStatus,
    ) -> list[OutboxMessage]: ...
    async def list_pending(self) -> list[OutboxMessage]: ...
