"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Any, Dict, List, Mapping

logger = ...
class PromptManager:
    """Lightweight wrapper around a `jinja2.Environment` for rendering LLM prompts.

    Improvements over the previous implementation:
    1) Uses `pathlib` for clearer path handling.
    2) Disables HTML auto-escaping for ``*.j2`` templates (prompts are plain text).
    3) Enables `StrictUndefined` so missing variables raise immediately.
    4) Removes superfluous whitespace with `trim_blocks` and `lstrip_blocks`.
    5) Adds basic debug logging through *structlog*.
    """
    def __init__(self, template_dir: str | Path = ...) -> None:
        ...
    
    def render_prompt(self, template_name: str, **context: Mapping[str, Any]) -> str:
        """Render *template_name* with *context*.

        The method will raise ``jinja2.exceptions.UndefinedError`` if the
        template references a variable that is not provided in *context*.
        """
        ...
    
    def messages_to_string(self, messages: List[Dict[str, Any]]) -> str:
        """Convert a list of messages to a string."""
        ...
    


