x-logging:
  logging: &default-logging
    driver: "local"
    options:
      max-size: "10m"
      max-file: "3"

services:
  label-studio:
    image: heartexlabs/label-studio:latest
    restart: unless-stopped
    container_name: label-studio
    ports:
      - "8080:8080"
#    volumes:
#      - ./data:/label-studio/data:rw
    env_file:
      - .env.prod
    command: label-studio-uwsgi
    depends_on:
      - db
      - minio

  ml-backend:
    container_name: label-studio-ml-backend-dev
    image: humansignal/ml-backend:v0
    build:
      context: ./backends/${LABEL_STUDIO_ML_BACKEND} 
      args:
        TEST_ENV: ${TEST_ENV}
    ports:
      - "9090:9090"
    volumes:
      - ./backends/${LABEL_STUDIO_ML_BACKEND}:/app:rw
    env_file:
      - .env.prod
    command: >
      label-studio-ml start . 
        --host 0.0.0.0 --port 9090
    deploy: 
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    # develop:
    #     watch:
    #       - path: ./backends/${LABEL_STUDIO_ML_BACKEND}
    #         target: /app
    #         action: sync
  db:
    image: pgautoupgrade/pgautoupgrade:13-alpine
    hostname: db
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d:ro
    env_file:
      - .env.prod
    ports:
      - "5433:5432"

  minio:
    image: quay.io/minio/minio:RELEASE.2024-02-13T15-35-11Z
    command: server /data --address ":9000" --console-address ":9009"
    restart: unless-stopped
    logging: *default-logging
    ports:
      - "9000:9000"
      - "9009:9009"
    volumes:
      - minio-data:/data
    env_file:
      - .env.prod

  prometheus:
    image: quay.io/prometheus/prometheus:v2.37.1
    restart: unless-stopped
    logging: *default-logging
    ports:
      - "9099:9099"
    volumes:
      - "./prometheus/minio/prometheus.yaml:/etc/prometheus/prometheus.yaml"
      - "prometheus-data:/prometheus"
    env_file:
      - .env.prod
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"



volumes:
  minio-data:
  prometheus-data:
