x-logging:
  logging: &default-logging
    driver: "local"
    options:
      max-size: "10m"
      max-file: "3"

services:
  label-studio:
    image: heartexlabs/label-studio:latest
    restart: unless-stopped
    container_name: label-studio-prod
    ports:
      - "8080:8080"
    env_file:
      - .env.prod
    command: label-studio-uwsgi
    depends_on:
      - db
      - minio

  ml-backend:
    container_name: label-studio-ml-backend-prod
    build:
      context: ./backends/${LABEL_STUDIO_ML_BACKEND} 
      args:
        TEST_ENV: ${TEST_ENV}
    ports:
      - "9090:9090"
    volumes:
      - ./backends/${LABEL_STUDIO_ML_BACKEND}:/app:rw
    env_file:
      - .env.prod
    command: gunicorn --chdir /app -b 0.0.0.0:9090 _wsgi:app

  db:
    image: pgautoupgrade/pgautoupgrade:13-alpine
    hostname: db
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d:ro
    env_file:
      - .env.prod
    ports:
      - "5433:5432"

  minio:
    image: quay.io/minio/minio:latest
    command: server /data --address ":9000" --console-address ":9009"
    restart: unless-stopped
    logging: *default-logging
    healthcheck:
      test: mc ready local 
      interval: 5s
      timeout: 5s
      retries: 3
    ports:
      - "9000:9000"
      - "9009:9009"
    volumes:
      - minio-data:/data
    env_file:
      - .env.prod

  minio-sync:
    image: minio/mc:latest
    env_file: 
      - .env.dev 
    depends_on:
      minio:
        condition: service_healthy
    volumes:
      - ./sync-minio.sh:/scripts/sync-minio.sh
      - ../data:/data:rw
    entrypoint: /bin/sh -c "/scripts/sync-minio.sh"
    restart: "no"
    profiles: ["sync"]

  prometheus:
    image: quay.io/prometheus/prometheus:v2.37.1
    restart: unless-stopped
    logging: *default-logging
    ports:
      - "9099:9099"
    volumes:
      - "./prometheus/minio/prometheus.yaml:/etc/prometheus/prometheus.yaml"
      - "prometheus-data:/prometheus"
    env_file:
      - .env.prod
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"



volumes:
  minio-data:
  prometheus-data:
