WORKFLOW_COMPILE_REQUESTED_SUBJECT = "jobs.workflow.compile.requested"
WORKFLOW_RUN_REQUESTED_SUBJECT = "jobs.workflow.run.requested"
NODE_RUN_EXECUTE_REQUESTED_SUBJECT = "jobs.node_run.execute.requested"

WORKFLOW_RUN_EVENT_SUBJECT_WILDCARD = "events.workflow_run.*"
NODE_RUN_EVENT_SUBJECT_WILDCARD = "events.node_run.*"
ARTIFACT_EVENT_SUBJECT_WILDCARD = "events.artifact.*"

WORKFLOW_RUN_QUEUED_EVENT_SUBJECT = "events.workflow_run.queued"
WORKFLOW_RUN_RUNNING_EVENT_SUBJECT = "events.workflow_run.running"
WORKFLOW_RUN_SUCCEEDED_EVENT_SUBJECT = "events.workflow_run.succeeded"
WORKFLOW_RUN_FAILED_RETRYABLE_EVENT_SUBJECT = "events.workflow_run.failed_retryable"
WORKFLOW_RUN_FAILED_PERMANENT_EVENT_SUBJECT = "events.workflow_run.failed_permanent"
WORKFLOW_RUN_CANCELLED_EVENT_SUBJECT = "events.workflow_run.cancelled"

NODE_RUN_QUEUED_EVENT_SUBJECT = "events.node_run.queued"
NODE_RUN_RUNNING_EVENT_SUBJECT = "events.node_run.running"
NODE_RUN_SUCCEEDED_EVENT_SUBJECT = "events.node_run.succeeded"
NODE_RUN_FAILED_RETRYABLE_EVENT_SUBJECT = "events.node_run.failed_retryable"
NODE_RUN_FAILED_PERMANENT_EVENT_SUBJECT = "events.node_run.failed_permanent"
NODE_RUN_CANCELLED_EVENT_SUBJECT = "events.node_run.cancelled"

ARTIFACT_CREATED_EVENT_SUBJECT = "events.artifact.created"

WORKFLOW_RUN_DELTA_SUBJECT_WILDCARD = "live.workflow_run.*"
NODE_RUN_DELTA_SUBJECT_WILDCARD = "live.node_run.*"
ARTIFACT_DELTA_SUBJECT_WILDCARD = "live.artifact.*"

DLQ_SUBJECT_WILDCARD = "dlq.>"
DLQ_NODE_RUN_EXECUTE_SUBJECT = "dlq.node_run.execute"


def workflow_run_event_subject(event_type: str) -> str:
    return f"events.workflow_run.{event_type}"


def node_run_event_subject(event_type: str) -> str:
    return f"events.node_run.{event_type}"


def artifact_event_subject(event_type: str) -> str:
    return f"events.artifact.{event_type}"

TASK_SUBJECTS = (
    WORKFLOW_COMPILE_REQUESTED_SUBJECT,
    WORKFLOW_RUN_REQUESTED_SUBJECT,
    NODE_RUN_EXECUTE_REQUESTED_SUBJECT,
)
EVENT_SUBJECTS = (
    WORKFLOW_RUN_EVENT_SUBJECT_WILDCARD,
    NODE_RUN_EVENT_SUBJECT_WILDCARD,
    ARTIFACT_EVENT_SUBJECT_WILDCARD,
)
LIVE_DELTA_SUBJECTS = (
    WORKFLOW_RUN_DELTA_SUBJECT_WILDCARD,
    NODE_RUN_DELTA_SUBJECT_WILDCARD,
    ARTIFACT_DELTA_SUBJECT_WILDCARD,
)
DLQ_SUBJECTS = (DLQ_SUBJECT_WILDCARD,)

__all__ = [
    "ARTIFACT_DELTA_SUBJECT_WILDCARD",
    "ARTIFACT_CREATED_EVENT_SUBJECT",
    "ARTIFACT_EVENT_SUBJECT_WILDCARD",
    "artifact_event_subject",
    "DLQ_NODE_RUN_EXECUTE_SUBJECT",
    "DLQ_SUBJECTS",
    "DLQ_SUBJECT_WILDCARD",
    "EVENT_SUBJECTS",
    "LIVE_DELTA_SUBJECTS",
    "NODE_RUN_DELTA_SUBJECT_WILDCARD",
    "NODE_RUN_CANCELLED_EVENT_SUBJECT",
    "NODE_RUN_EVENT_SUBJECT_WILDCARD",
    "NODE_RUN_EXECUTE_REQUESTED_SUBJECT",
    "NODE_RUN_FAILED_PERMANENT_EVENT_SUBJECT",
    "NODE_RUN_FAILED_RETRYABLE_EVENT_SUBJECT",
    "NODE_RUN_QUEUED_EVENT_SUBJECT",
    "NODE_RUN_RUNNING_EVENT_SUBJECT",
    "NODE_RUN_SUCCEEDED_EVENT_SUBJECT",
    "node_run_event_subject",
    "TASK_SUBJECTS",
    "WORKFLOW_RUN_CANCELLED_EVENT_SUBJECT",
    "WORKFLOW_COMPILE_REQUESTED_SUBJECT",
    "WORKFLOW_RUN_DELTA_SUBJECT_WILDCARD",
    "WORKFLOW_RUN_EVENT_SUBJECT_WILDCARD",
    "WORKFLOW_RUN_FAILED_PERMANENT_EVENT_SUBJECT",
    "WORKFLOW_RUN_FAILED_RETRYABLE_EVENT_SUBJECT",
    "WORKFLOW_RUN_QUEUED_EVENT_SUBJECT",
    "WORKFLOW_RUN_REQUESTED_SUBJECT",
    "WORKFLOW_RUN_RUNNING_EVENT_SUBJECT",
    "WORKFLOW_RUN_SUCCEEDED_EVENT_SUBJECT",
    "workflow_run_event_subject",
]
