path: ''
name: default_dataset
force_download: false
trust_remote_code: true
keep_in_memory: false
num_proc: 8
split: train
streaming: false
column_map:
  image_column: image
  ground_truth_column: ground_truth
  boxes_column: bboxes
  labels_column: labels
  tokens_column: tokens
full_schematisms: []
partial_schematisms: []
positive_samples: 10
negative_samples: 5
classes_to_remove: []
languages: []
