path: "artpods56/AIOsrodekSchematisms"
name: "default"
force_download: false
trust_remote_code: true
keep_in_memory: false
num_proc: 8
seed: 42
split: "train"
streaming: false

image_column_name: "image"
ground_truth_column_name: "results"

#Lublin 1870,
#Płock 1880 i 1882, Warszawa 1870 i 1872 (brak podanego materiału budowalnego), Sejny 1874

positive_samples: 100000
negative_samples: 100000
full_schematisms:
#  - "lublin_1870"
  - "plock_1880"
  - "plock_1882"
#  - "warszawa_1870"
#  - "warszawa_1872"
#  - "sejny_1874"
#  - "wloclawek_1872"
#  - "wloclawek_1873"
#  - "tarnow_1870"
#  - "chelmno_1871"

partial_schematisms: []
#  - "plock_1939"
#  - "chelmno_1938"
#  - "lublin_1939"
#  - "sandomierz_1876"
#  - "sejny_1877"
#  - "zmudz_1863"


