[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "grafy-plugin-llm"
version = "0.1.0"
requires-python = "==3.14.*"
dependencies = [
    "mistralai>=2.6.0",
    "grafy-core",
    "openai>=2.0.0",
    "pydantic",
]

[project.entry-points."grafy.plugins"]
llm = "grafy_plugin_llm.plugin:LLM"

[tool.uv.sources]
grafy-core = { workspace = true }

[tool.basedpyright]
extends = "../../pyproject.toml"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
