path: ''
name: default_dataset
force_download: false
trust_remote_code: true
keep_in_memory: false
num_proc: 8
split: train
streaming: false
seed: 42
eval_size: 0.2
test_size: 0.1
image_column_name: image_pil
text_column_name: words
boxes_column_name: bboxes
label_column_name: labels
