[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "grafy-plugin-gis"
version = "0.1.0"
requires-python = "==3.14.*"
dependencies = [
    "httpx>=0.28.1",
    "grafy-core",
    "pydantic",
    "pyproj>=3.7.0",
    "shapely>=2.1.0",
    "truststore>=0.10.4",
]

[project.entry-points."grafy.plugins"]
gis = "grafy_plugin_gis.plugin:GIS"

[tool.uv.sources]
grafy-core = { workspace = true }

[tool.basedpyright]
extends = "../../pyproject.toml"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
