[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "notarius-api"
version = "0.1.0"
requires-python = "==3.12.9"
dependencies = [
    "cryptography>=45.0.0",
    "fastapi>=0.123.0",
    "notarius-core",
    "notarius-persistence",
    "notarius-storage",
    "pillow",
    "prefect==3.6.21",
    "pydantic",
    "pydantic-settings>=2.12.0",
    "starlette<1.0.0",
    "uvicorn>=0.38.0",
]

[tool.uv.sources]
notarius-core = { workspace = true }
notarius-persistence = { workspace = true }
notarius-storage = { workspace = true }

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
