[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "notarius-api"
version = "0.1.0"
requires-python = "==3.12.9"
dependencies = [
    "faststream[nats]>=0.6.0",
    "fastapi>=0.123.0",
    "mistralai>=2.5.0",
    "notarius-core",
    "notarius-messaging",
    "notarius-persistence",
    "notarius-shared",
    "notarius-storage",
    "notarius-worker",
    "pdfplumber>=0.11.7",
    "pydantic",
    "python-multipart>=0.0.20",
    "uvicorn>=0.38.0",
]

[tool.uv.sources]
notarius-core = { workspace = true }
notarius-messaging = { workspace = true }
notarius-persistence = { workspace = true }
notarius-shared = { workspace = true }
notarius-storage = { workspace = true }
notarius-worker = { workspace = true }

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
